M48
; DRILL file KiCad 10.0.4 date 2026-07-30T17:46:24
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-30T17:46:24+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.508
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X94.39Y-34.16
X100.17Y-34.16
T2
X26.416Y-50.8
X27.178Y-30.226
X46.736Y-30.48
X47.244Y-50.8
M30
